platform :ios, '7.1'
pod 'AFNetworking'
pod 'Reachability'
pod 'MBProgressHUD'
pod 'FMDB'
pod 'JSONKit-NoWarning'
pod 'RegexKitLite'
pod 'jastor'
pod 'SDWebImage'
xcodeproj 'yuqing2/yuqing2.xcodeproj'
